apiVersion: v1
kind: Service
metadata:
  name: userapp
  labels:
      app: userapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3030
      protocol: TCP
  selector:
    app: userapp